export const decalreOptions = [
  {
    key: '1',
    value: 'None',
  },
  {
    key: '2',
    value: 'Default',
  },
];

export const fieldTypes = {
  edit: 'Edit',
  date: 'Date',
  combo: 'Combo',
  checkbox: 'Checkbox',
  radioGroup: 'RadioGroup',
  grid: 'Grid',
};

export const newDocumentData = {
  Document: {
    New: 1,
    Fields: {
      User: {
        Field: [
          {
            FieldNumber: 21,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Title',
            Data: '',
            Mandatory: true,
          },
          {
            FieldNumber: 23,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: true,
            Length: 1000,
            Label: 'Description',
            Data: '',
            Mandatory: false,
          },
          {
            FieldNumber: 24,
            Type: 'Date',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Date',
            Date: {
              Month: '04',
              Year: 2023,
              Minute: '05',
              Second: 53,
              Hour: 20,
              Day: 26,
            },
            Mandatory: true,
          },
          {
            FieldNumber: 41,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Name of Creator',
            Data: '',
            Mandatory: false,
          },
          {
            FieldNumber: 42,
            Type: 'Date',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Date of Creation',
            Date: {
              Month: '04',
              Year: 2023,
              Minute: '05',
              Second: 53,
              Hour: 20,
              Day: 26,
            },
            Mandatory: false,
          },
          {
            FieldNumber: 43,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Name(s) of Co-Worker(s)',
            Data: '',
            Mandatory: false,
          },
          {
            FieldNumber: 44,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Name(s) of Reviewer(s)',
            Data: '',
            Mandatory: false,
          },
          {
            FieldNumber: 45,
            Type: 'Date',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Date of Review',
            Date: {
              Month: '04',
              Year: 2023,
              Minute: '05',
              Second: 53,
              Hour: 20,
              Day: 26,
            },
            Mandatory: false,
          },
          {
            FieldNumber: 46,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Name of Approver',
            Data: '',
            Mandatory: false,
          },
          {
            FieldNumber: 47,
            Type: 'Date',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Date of Approval',
            Date: {
              Month: '04',
              Year: 2023,
              Minute: '05',
              Second: 53,
              Hour: 20,
              Day: 26,
            },
            Mandatory: false,
          },
          {
            FieldNumber: 48,
            Type: 'Edit',
            Numerical: false,
            Thesaurus: false,
            Length: 100,
            Label: 'Keyword(s)',
            Data: '',
            Mandatory: false,
          },
        ],
      },
    },
    Profiles: {
      Profile: [
        {
          No: 1,
          Field: [21, 23, 24],
          Name: 'General Info.',
        },
        {
          No: 2,
          Field: [41, 42],
          Name: 'Creator',
        },
        {
          No: 3,
          Field: 43,
          Name: 'Co-Worker(s)',
        },
        {
          No: 4,
          Field: [44, 45],
          Name: 'Reviewer(s)',
        },
        {
          No: 5,
          Field: [46, 47],
          Name: 'Approver',
        },
        {
          No: 6,
          Field: 48,
          Name: 'Keyword(s)',
        },
      ],
    },
    Images: {Browse: 'yes'},
    Upload: true,
    DeclareDocument: true,
    Declared: false,
  },
  MimeTypes: {
    MimeType: [
      {
        Extension: 'fdf',
        Mime: 'application/pdf',
        Application: 'Adobe Acrobat',
        OCR: true,
      },
      {
        Extension: 'pdf',
        Mime: 'application/pdf',
        Application: 'Adobe Acrobat',
        OCR: true,
      },
      {
        Extension: 'iff',
        Mime: '?',
        Application: 'ARC',
        OCR: true,
      },
      {
        Extension: 'cad',
        Mime: 'image/vnd.dxf',
        Application: 'Autodesk',
        OCR: true,
      },
      {
        Extension: 'dwf',
        Mime: 'image/vnd.dxf',
        Application: 'Autodesk',
        OCR: true,
      },
      {
        Extension: 'dwg',
        Mime: 'image/vnd.dxf',
        Application: 'Autodesk',
        OCR: true,
      },
      {
        Extension: 'dxf',
        Mime: 'image/vnd.dxf',
        Application: 'Autodesk',
        OCR: true,
      },
      {
        Extension: 'skf',
        Mime: 'image/vnd.dxf',
        Application: 'Autodesk',
        OCR: true,
      },
      {
        Extension: '?',
        Mime: '//',
        Application: 'Crystal Reports',
        OCR: true,
      },
      {
        Extension: 'gwe',
        Mime: 'application/gwe',
        Application: 'Groupwise email',
        OCR: true,
      },
      {
        Extension: 'jpeg',
        Mime: 'image/jpeg',
        Application: 'image/jpeg',
        OCR: false,
      },
      {
        Extension: 'htm',
        Mime: 'text/html',
        Application: 'Internet Explorer',
        OCR: true,
      },
      {
        Extension: 'html',
        Mime: 'text/html',
        Application: 'Internet Explorer',
        OCR: true,
      },
      {
        Extension: 'mht',
        Mime: 'message/rfc822',
        Application: 'Internet Explorer',
        OCR: true,
      },
      {
        Extension: 'wmf',
        Mime: 'text/html',
        Application: 'Internet Explorer',
        OCR: true,
      },
      {
        Extension: 'mdb',
        Mime: '?',
        Application: 'MS Access',
        OCR: true,
      },
      {
        Extension: 'axg',
        Mime: '?',
        Application: 'MS Autoroute Express',
        OCR: true,
      },
      {
        Extension: 'csv',
        Mime: 'application/vnd.ms-excel',
        Application: 'MS Excel',
        OCR: true,
      },
      {
        Extension: 'xls',
        Mime: 'application/vnd.ms-excel',
        Application: 'MS Excel',
        OCR: true,
      },
      {
        Extension: 'xlsx',
        Mime: 'application/vnd.ms-excel',
        Application: 'MS Excel',
        OCR: true,
      },
      {
        Extension: 'xlv',
        Mime: 'application/vnd.ms-excel',
        Application: 'MS Excel',
        OCR: true,
      },
      {
        Extension: '?',
        Mime: '?',
        Application: 'MS Front Page',
        OCR: true,
      },
      {
        Extension: 'obd',
        Mime: 'application/x-msbinder',
        Application: 'MS Office Binder',
        OCR: true,
      },
      {
        Extension: 'msg',
        Mime: 'appication/mail',
        Application: 'MS Outlook',
        OCR: true,
      },
      {
        Extension: 'bmp',
        Mime: 'image/bmp',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'gif',
        Mime: 'image/gif',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'jpg',
        Mime: 'image/jpeg',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'pcd',
        Mime: '?',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'pcx',
        Mime: 'image/x-pcx',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'png',
        Mime: 'image/png',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'tga',
        Mime: '?',
        Application: 'MS Photo Editor',
        OCR: true,
      },
      {
        Extension: 'pps',
        Mime: 'application/vnd.ms-powerpoint',
        Application: 'MS Powerpoint',
        OCR: true,
      },
      {
        Extension: 'ppt',
        Mime: 'application/vnd.ms-powerpoint',
        Application: 'MS Powerpoint',
        OCR: true,
      },
      {
        Extension: 'pptx',
        Mime: 'application/vnd.ms-powerpoint',
        Application: 'MS Powerpoint',
        OCR: true,
      },
      {
        Extension: 'mpp',
        Mime: 'application/vnd.ms-project',
        Application: 'MS Project',
        OCR: true,
      },
      {
        Extension: 'vsd',
        Mime: 'application/vnd.visio',
        Application: 'MS Visio',
        OCR: true,
      },
      {
        Extension: 'vsdx',
        Mime: 'application/vnd.visio',
        Application: 'MS Visio',
        OCR: true,
      },
      {
        Extension: 'doc',
        Mime: 'application/msword',
        Application: 'MS Word',
        OCR: true,
      },
      {
        Extension: 'docx',
        Mime: 'application/msword',
        Application: 'MS Word',
        OCR: true,
      },
      {
        Extension: 'dot',
        Mime: 'application/msword',
        Application: 'MS Word',
        OCR: true,
      },
      {
        Extension: 'rtf',
        Mime: 'application/msword',
        Application: 'MS Word',
        OCR: true,
      },
      {
        Extension: 'eml',
        Mime: 'setEditTransferFolderVisible',
        Application: 'Outlook',
        OCR: true,
      },
      {
        Extension: 'tif',
        Mime: 'image/tiff',
        Application: 'Valid Viewer',
        OCR: true,
      },
      {
        Extension: 'tiff',
        Mime: 'image/tiff',
        Application: 'Valid Viewer',
        OCR: true,
      },
      {
        Extension: 'chm',
        Mime: '?',
        Application: 'Windows Help File',
        OCR: true,
      },
      {
        Extension: 'aif',
        Mime: 'audio/aiff',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'aifc',
        Mime: 'audio/aiff',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'aiff',
        Mime: 'audio/aiff',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'asf',
        Mime: 'video/x-ms-asf',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'asx',
        Mime: 'application/x-mplayer2',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'au',
        Mime: 'audio/basic',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'avi',
        Mime: 'video/avi',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'cda',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'm1v',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'm3u',
        Mime: 'audio/mpegurl',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mid',
        Mime: 'audio/midi',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'midi',
        Mime: 'audio/midi',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mp2',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mp3',
        Mime: 'audio/mp3',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mpa',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mpe',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mpeg',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'mpg',
        Mime: 'video/mpeg',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'rmi',
        Mime: 'audio/midi',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'snd',
        Mime: 'audio/basic',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wav',
        Mime: 'audio/wav',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wax',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wm',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wma',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wmv',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wmx',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'wvx',
        Mime: '?',
        Application: 'Windows Media Player',
        OCR: true,
      },
      {
        Extension: 'zip',
        Mime: 'application/zip',
        Application: 'Winzip',
        OCR: true,
      },
      {
        Extension: 'txt',
        Mime: 'text/plain',
        Application: 'Wordpad',
        OCR: true,
      },
    ],
  },
  System: {
    Hit: '',
    User: {
      Full_Name: 'System Administrator',
      No: 10,
      Name: 'sysadmin',
    },
    Thesaurus: true,
    RecordTypeList: {
      RecordType: [
        {
          DisposalSchedule: 0,
          Number: 0,
          Security: {
            GroupList: '',
            UserList: '',
          },
          Default: '',
          Name: 'Default',
        },
        {
          DisposalSchedule: 3,
          Number: 1,
          Security: {
            GroupList: {Group: 6},
            UserList: {User: 10},
          },
          Name: 'RT7',
        },
        {
          DisposalSchedule: 3,
          Number: 2,
          Security: {
            GroupList: {Group: 6},
            UserList: {User: 10},
          },
          Name: 'RT8',
        },
        {
          DisposalSchedule: 3,
          Number: 3,
          Security: {
            GroupList: {Group: 6},
            UserList: {User: 10},
          },
          Name: 'RT1',
        },
        {
          DisposalSchedule: 3,
          Number: 4,
          Security: {
            GroupList: {Group: [6, 3, 1]},
            UserList: {User: [10, 13, 14]},
          },
          Name: 'RT2',
        },
      ],
    },
    Bundle: 'G',
    Search: 0,
    DatabaseName: 'ABC Organization',
    Doctype: 1,
    DB: 4,
  },
};
