export const usersList = [
  {
    email: 'No Email set for this user',
    No: 1,
    userName: 'nextno',
    Full_Name: 'used for next number',
  },
  {
    email: 'none',
    No: 10,
    userName: 'sysadmin',
    Full_Name: 'System Administrator',
  },
  {
    email: 'No Email set for this user',
    No: 11,
    userName: 'update',
    Full_Name: 'Update Administrator',
  },
  {
    email: 'No Email set for this user',
    No: 12,
    userName: 'ocr',
    Full_Name: 'OCR Administrator',
  },
  {
    email: 'asim.amin@centillionsol.com',
    No: 13,
    userName: 'Asim',
    Full_Name: 'Asim Amin',
  },
  {
    email: 'junaid@centillionsol.com',
    No: 14,
    userName: 'Junaid',
    Full_Name: 'Junaid Manzoor',
  },
  {
    email: 'ali@centillionsol.com',
    No: 15,
    userName: 'Ali',
    Full_Name: 'Ali Sajjad',
  },
  {
    email: 'atif@cfe-solutions.co.uk',
    No: 16,
    userName: 'Atif',
    Full_Name: 'Atif Amin',
  },
  {email: 'none', No: 18, userName: 'User', Full_Name: 'User Admin'},
  {email: 'none', No: 20, userName: 'Usmanali', Full_Name: 'Usman Ali'},
  {email: 'none', No: 21, userName: 'Saif', Full_Name: 'SaifAli'},
  {email: 'none', No: 22, userName: 'Faizan', Full_Name: 'Faizan Ali'},
  {email: 'none', No: 23, userName: 'Shahbaz', Full_Name: 'Shahbaz '},
  {email: 'none', No: 24, userName: 'Ahmed', Full_Name: 'Ahmed'},
  {
    email: 'none',
    No: 25,
    userName: 'iammustashfa',
    Full_Name: 'Mustashfa Ali Naqvi ',
  },
  {email: 'none', No: 26, userName: 'Hashir', Full_Name: 'Hashir Saleem'},
  {email: 'none', No: 27, userName: 'Fauzia', Full_Name: 'Fauzia Najam'},
];

export const groupsList = [
  {
    id: 1,
    name: 'Hello',
    active: true,
    createdAt: '2023-03-29T20:40:49+01:00',
    users: [
      {
        email: 'atif@cfe-solutions.co.uk',
        No: 16,
        userName: 'Atif',
        Full_Name: 'Atif Amin',
      },
      {email: 'none', No: 20, userName: 'Usmanali', Full_Name: 'Usman Ali'},
      {
        email: 'junaid@centillionsol.com',
        No: 14,
        userName: 'Junaid',
        Full_Name: 'Junaid Manzoor',
      },
      {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
    ],
    groupMessageHistory: {
      id: 248,
      messageBody: 'hello',
      sender: {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
      createdAt: '2023-03-29T20:41:19+01:00',
    },
    unreadMessageCount: 3,
  },
  {
    id: 2,
    name: 'Test Group',
    active: true,
    createdAt: '2023-03-29T20:42:02+01:00',
    users: [
      {
        email: 'atif@cfe-solutions.co.uk',
        No: 16,
        userName: 'Atif',
        Full_Name: 'Atif Amin',
      },
      {
        email: 'junaid@centillionsol.com',
        No: 14,
        userName: 'Junaid',
        Full_Name: 'Junaid Manzoor',
      },
      {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
    ],
    groupMessageHistory: {
      id: 249,
      messageBody: 'hello',
      sender: {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
      createdAt: '2023-03-29T20:42:48+01:00',
    },
    unreadMessageCount: 2,
  },
  {
    id: 3,
    name: 'new',
    active: true,
    createdAt: '2023-03-29T20:43:13+01:00',
    users: [
      {
        email: 'junaid@centillionsol.com',
        No: 14,
        userName: 'Junaid',
        Full_Name: 'Junaid Manzoor',
      },
      {
        email: 'atif@cfe-solutions.co.uk',
        No: 16,
        userName: 'Atif',
        Full_Name: 'Atif Amin',
      },
      {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
    ],
    groupMessageHistory: {
      id: 250,
      messageBody: 'Hi',
      sender: {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
      createdAt: '2023-03-29T20:43:21+01:00',
    },
    unreadMessageCount: 0,
  },
  {
    id: 4,
    name: 'help',
    active: true,
    createdAt: '2023-03-29T20:53:20+01:00',
    users: [
      {
        email: 'atif@cfe-solutions.co.uk',
        No: 16,
        userName: 'Atif',
        Full_Name: 'Atif Amin',
      },
      {
        email: 'junaid@centillionsol.com',
        No: 14,
        userName: 'Junaid',
        Full_Name: 'Junaid Manzoor',
      },
      {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
    ],
    groupMessageHistory: {
      id: 251,
      messageBody: 'hy',
      sender: {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
      createdAt: '2023-03-29T20:57:55+01:00',
    },
    unreadMessageCount: 0,
  },
  {
    id: 5,
    name: 'hy',
    active: true,
    createdAt: '2023-03-29T20:57:48+01:00',
    users: [
      {
        email: 'atif@cfe-solutions.co.uk',
        No: 16,
        userName: 'Atif',
        Full_Name: 'Atif Amin',
      },
      {
        email: 'none',
        No: 10,
        userName: 'sysadmin',
        Full_Name: 'System Administrator',
      },
    ],
    groupMessageHistory: {
      id: 252,
      messageBody: 'help',
      sender: {
        email: 'none',
        No: 1,
        userName: 'Nayyer Ali',
        Full_Name: 'System Administrator',
      },
      createdAt: '2023-03-29T20:57:59+01:00',
    },
    unreadMessageCount: 0,
  },
];

export const chats = [
  {
    id: 69,
    createdAt: '2023-03-24T20:25:24Z',
    updatedAt: '2023-03-24T20:25:24Z',
    active: true,
    messageBody: 'fe',
    userId: 15,
    userName: 'Ali Sajjad',
    unreadMessageCount: 0,
  },
  {
    id: 208,
    createdAt: '2023-03-28T22:28:36+01:00',
    updatedAt: '2023-03-28T22:28:36+01:00',
    active: true,
    messageBody: 'ffrf',
    userId: 24,
    userName: 'Ahmed',
    unreadMessageCount: 3,
  },
  {
    id: 229,
    createdAt: '2023-03-29T19:56:44+01:00',
    updatedAt: '2023-03-29T19:56:44+01:00',
    active: true,
    messageBody: "hy'",
    userId: 14,
    userName: 'Junaid Manzoor',
    unreadMessageCount: 0,
  },
  {
    id: 233,
    createdAt: '2023-03-29T19:57:29+01:00',
    updatedAt: '2023-03-29T19:57:29+01:00',
    active: true,
    messageBody: 'hhy',
    userId: 13,
    userName: 'Asim Amin',
    unreadMessageCount: 0,
  },
  {
    id: 238,
    createdAt: '2023-03-29T20:03:30+01:00',
    updatedAt: '2023-03-29T20:03:30+01:00',
    active: true,
    messageBody: 'hy',
    userId: 22,
    userName: 'Faizan Ali',
    unreadMessageCount: 0,
  },
  {
    id: 241,
    createdAt: '2023-03-29T20:08:40+01:00',
    updatedAt: '2023-03-29T20:08:40+01:00',
    active: true,
    messageBody: 'helo',
    userId: 12,
    userName: 'OCR Administrator',
    unreadMessageCount: 0,
  },
  {
    id: 242,
    createdAt: '2023-03-29T20:09:01+01:00',
    updatedAt: '2023-03-29T20:09:01+01:00',
    active: true,
    messageBody: 'hy',
    userId: 23,
    userName: 'Shahbaz ',
    unreadMessageCount: 0,
  },
  {
    id: 246,
    createdAt: '2023-03-29T20:32:13+01:00',
    updatedAt: '2023-03-29T20:32:13+01:00',
    active: true,
    messageBody: 'hi',
    userId: 16,
    userName: 'Atif Amin',
    unreadMessageCount: 0,
  },
];
