const AppRoutes = {
  ChangePassword: 'ChangePassword',
  ForgotPassword: 'ForgotPassword',
  Login: 'Login',
  SelectDatabase: 'SelectDatabase',
  Chats: 'Chats',
  Messages: 'Messages',
  AllUsers: 'AllUsers',
  AllGroups: 'AllGroups',
  AddOrUpdateGroup: 'AddOrUpdateGroup',
  Home: 'Home',
  Settings: 'Settings',
  AddOrUpdateReminder: 'AddOrUpdateReminder',
  Reminders: 'Reminders',
  BottomNavigation: 'BottomNavigation',
  AddDocument: 'AddDocument',
  AddFolder: 'AddFolder',
  RecentSearches: 'RecentSearches',
  DocumentDetails: 'DocumentDetails',
  ReminderDetails: 'ReminderDetails',
  AddUserToGroup: 'AddUserToGroup',
  DocumentsList: 'DocumentsList',
  CheckoutDocument: 'CheckoutDocument',
  DocumentIndex: 'DocumentIndex',
  DocumentProperties: 'DocumentProperties',
  DocumentVersionInfo: 'DocumentVersionInfo',
  EditDocument: 'EditDocument',
  SignDocument: 'SignDocument',
};

export default AppRoutes;
